[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
itertools = "0.10.5"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "aoc_benchmarks"
harness = false
